### ISSUE TITLE
Upgrade dependencies to Redis 0.12.x

### ISSUE THREAD

**Issue by claudioc** [othiym23/cls-redis#3]
Hi, would you mind taking a look at if cls-redis correctly works with the latest redis module? It seems so, but I cannot be 100% sure.

**Comment by enicholson** [comment]
+1

**Comment by othiym23** [comment]
Fixed via 041d70f, which passed all the tests I ran. Someday I'm going to have time for `cls@4`, which will remove the need for all these shims...

Thanks for the prod to both of you!
